### ISSUE TITLE
compute_coordinates.py input error

### ISSUE THREAD

**Issue by SinanGncgl** [Lotayou/everybody_dance_now_pytorch#10]
When i prepare the dataset exactly what instructions say, and run the command;

`python ./pose_estimator/compute_coordinates.py`

It gives me the following error.

`Traceback (most recent call last):
  File "pose_estimator/compute_coordinates_for_video.py", line 258, in <module>
    cord = cordinates_from_image_file(img, model=model)
  File "pose_estimator/compute_coordinates_for_video.py", line 188, in cordinates_from_image_file
    output1, output2 = model.predict(imageToTest_padded)
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1096, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2382, in _standardize_user_data
    exception_prefix='input')
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 362, in standardize_input_data
    ' but got array with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_5 to have shape (None, None, 3) but got array with shape (184, 103, 4)`

Thank you.

**Comment by SinanGncgl** [comment]
After rename my images `00001.png` , `00002.png`..., error disappears and gives this error;

`File "pose_estimator/compute_coordinates_for_video.py", line 252, in <module>
    tmp = imread(os.path.join(img_dir, img_list[0]))
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/Users/sinangencoglu/anaconda3/envs/sinandl/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'`

**Comment by Lotayou** [comment]
Seems that your video frames contain 4 channels, removing the alpha channel and use RGB input should work.
