### ISSUE TITLE
pretrained pose_estimator error

### ISSUE THREAD

**Issue by caokyhieu** [Lotayou/everybody_dance_now_pytorch#15]
I got the error when runing  `python ./pose_estimator/compute_coordinates_for_video.py`:
`2020-09-02 08:55:35.129558: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-02 08:55:35.129593: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "./pose_estimator/compute_coordinates_for_video.py", line 251, in <module>
    model = load_model('./pose_estimator/pose_estimator.h5')
  File "/opt/conda/envs/EDN/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/opt/conda/envs/EDN/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    f = h5py.File(filepath, mode='r')
  File "/opt/conda/envs/EDN/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/conda/envs/EDN/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file read failed: time = Wed Sep  2 08:55:36 2020
, filename = './pose_estimator/pose_estimator.h5', file descriptor = 4, errno = 5, error message = 'Input/output error', buf = 0x7fffd750fdb0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)`

It seems the pose_estimator.h5 file had been broken. Is there anybody had faced the same problem and how to fix it?

Thanks

**Comment by chuqiaoz** [comment]
same problem here
