### ISSUE TITLE
Broken Pipe error

### ISSUE THREAD

**Issue by guancheng817** [Lotayou/everybody_dance_now_pytorch#4]
I execute the script   sh ./scripts/test_full_512.sh 
Then appear the error as follows:
/media/ouc/4T_B/gc/everybody_dance_now_pytorch/models/pose2vidHD_model.py:146: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_label = Variable(input_label, volatile=infer)
100%|█████████████████████████████████████████| 500/500 [01:58<00:00,  4.19it/s]
Unknown encoder 'libx264'
Traceback (most recent call last):
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 727, in _append_data
    self._proc.stdin.write(im.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_video.py", line 60, in <module>
    writer.append_data(im)
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/imageio/core/format.py", line 500, in append_data
    return self._append_data(im, total_meta)
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 734, in _append_data
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/home/ouc/miniconda3/bin/ffmpeg -y -f rawvideo -vcodec rawvideo -s 480x480 -pix_fmt rgb24 -r 25.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -crf 25 -v warning /media/ouc/4T_B/gc/everybody_dance_now_pytorch/results/everybody_dance_now_temporal/latest/test_clip.avi

FFMPEG STDERR OUTPUT:

How can I fix the problem. Thanks

**Comment by Haoru** [comment]
I have met the same problem. Have you solved it?

**Comment by Lotayou** [comment]
It seems like the ffmpeg plugin on your server is malfunctioning. You can check if your ffmpeg plugin is working properly by testing with the following script:

```
import imageio as imo

video_name = 'test.avi' #your video name#
reader = imo.get_reader(video_name)
writer = imo.get_reader('write_out.avi')

for im in reader:
    writer.append_data(im)
writer.close()
```

See if the script executes without error, and check if the generated video file `write_out.avi` is the same as your testing video. 
Also, try to reinstall imageio package and see if that helps solve the problem.
